# Generated by Django 3.1.3 on 2021-11-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='event_id',
            new_name='event',
        ),
    ]
