# Generated by Django 3.1.3 on 2021-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210119_1235'),
        ('events', '0004_auto_20210616_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='categories.Category'),
        ),
    ]
