# Generated by Django 3.1.3 on 2021-11-09 13:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20211109_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('22252e9b-c9cb-4ab0-affb-bb15bd9cc7d5'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
