# Generated by Django 3.1.3 on 2021-11-09 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211109_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('4d4fee9f-98b3-4dc8-9c6c-ae87f1849bd0'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
