# Generated by Django 3.1.3 on 2021-08-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210715_1910'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table='Events',
        ),
    ]
