# Generated by Django 3.1.3 on 2021-11-09 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20211109_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('e9c56d2e-caf5-43ee-9485-244291bea69b'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
