# Generated by Django 3.1.3 on 2021-11-09 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211109_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('472d7aff-890a-4ccb-a068-e32de14fb74c'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
