# Generated by Django 3.1.3 on 2021-11-09 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20211109_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('27b95af7-b3b4-4a07-95c2-122023bf940a'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
