# Generated by Django 3.1.3 on 2021-11-09 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20211109_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='image_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='id',
            field=models.CharField(default=uuid.UUID('b7ef4395-9aaf-4082-8b72-ee00dc76cf7d'), max_length=36, primary_key=True, serialize=False),
        ),
    ]
