# Generated by Django 3.1.3 on 2021-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20211111_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='image_dominant_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
