# Generated by Django 3.1.3 on 2021-11-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20211111_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/11-2021/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, max_length=255, upload_to='events/11-2021/'),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image_dominant_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
