# Generated by Django 3.1.3 on 2021-11-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20211123_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_dominant_color',
            new_name='dominant_color',
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_height',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='eventimage',
            old_name='image_width',
            new_name='width',
        ),
    ]
