# Generated by Django 3.1.3 on 2022-07-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_eventimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='author',
        ),
    ]
