# Generated by Django 3.1.3 on 2022-07-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizer_abbreviation'),
        ('events', '0019_auto_20220713_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizers.organizer'),
        ),
    ]
