# Generated by Django 3.1.3 on 2022-07-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer',
            new_name='organization',
        ),
    ]
