# Generated by Django 3.0.7 on 2021-01-18 16:00

from django.db import migrations, models
import organizers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.CharField(default=organizers.models.id_gen, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organizers',
            },
        ),
    ]
