# Generated by Django 3.1.3 on 2021-08-22 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organizer',
            table='Organizers',
        ),
    ]
