# Generated by Django 3.1.3 on 2022-07-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
