# Generated by Django 3.1.3 on 2022-07-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220713_2049'),
        ('events', '0021_auto_20220713_2059'),
        ('organizers', '0002_organizer_abbreviation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organizer',
            new_name='Organization',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='Organizations',
        ),
    ]
