# Generated by Django 3.1.3 on 2021-01-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='Accounts',
        ),
    ]
