# Generated by Django 3.1.3 on 2021-12-12 14:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.path_and_rename),
        ),
    ]
